[project]
name = "features"
version = "0.1.0"
description = "Central repository for Vindicta Platform feature testing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "behave>=1.2.6",
]

[tool.uv]
package = true
